var myName ="Maryam Curnal";
var para1 =document.getElementById("p1");
para1.textContent = myName;
let n1 = 47;
let n2 = 47;
n1 = 32;
n2 = 23;
var numberSum;
numberSum = n1 + n2;
document.getElementById("p2").textContent = numberSum;
var numberMult;
numberMult = n1 * n2;
document.getElementById("p3").textContent = numberMult;
var myNameAddNum;
myNameAddNum = n1 + myName;
document.getElementById("p4").textContent = myNameAddNum;
var myNameMultNum;
myNameMultNum = n1 * myName;
document.getElementById("p5").textContent = myNameMultNum;
var ageCompare;
ageCompare = n1 < 28;
document.getElementById("p6").textContent = ageCompare;
